mysql:
  host: service
  port: 3306
  db: gvb
  user: root
  password: abc
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site_info:
  created_at: "2024-7-14"
  bei_an: 陕ICP备2021010653号-3
  title: lianghl
  qq_image: static/qq.png
  version: 6.0.2
  email: 2879343819@qq.com
  wechat_image: static/wechat.png
  name: lianghl
  job: student
  addr: 陕西西安
  slogan: "11222266"
  slogan_en: i love you, are you love me?
  web: http://www.lianghl.top
  bilibili_url: https://space.bilibili.com/1771877543
  gitee_url: https://gitee.com/xlyty
  github_url: https://github.com/lianghl112266package config
qq:
  app_id: xxx
  key: xx
  redirect: http://xx.xx.com/login?flag=qqq
qi_niu:
  enable: false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: lianghl
  cdn: xx://xx.xx.com/
  zone: xx
  prefix: lianghl
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 2879343819@qq.com
  password: abcd123.
  default_from_email: lianghl
  use_ssl: true
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
